### ISSUE TITLE
你这咋node_modules咋传上来了

### ISSUE THREAD

**Issue by luoyjx** [wenshiqi0/koa_serv#1]
如题

PS：没有演示页么

**Comment by wenshiqi0** [comment]
有个演示页面页面 但是主要是对socket.io的，那个node_nodules之前是在windows下面开发的，全局路径有问题，所以一直用的局部路径，而且这个页面很好写的，全部是按照路径映射的，不用配置，还要是在设计的时候没有很好的动静分离，这个最主要是对webapp和原生app的，所以页面就没有太做这个

**Comment by wenshiqi0** [comment]
我之后会删掉的

**Comment by wenshiqi0** [comment]
我之后会吧动静分离也做了 并看看整合一下react做一些简单的页面的

**Comment by luoyjx** [comment]
关注~
